- src/make_custom_pi_os
Use this since versions(jessie, stretch etc.) change and discrepancies with dates in folder and file exist
> Find exact file instead of using date

- src/custompios
In #8, 7-zip has been implemented for extracting the image files. Recently I noticed that on subsequent builds, thebuild gets interrupted when calling `7za` as it asks whether to overwrite existing files. This PR fixes the issue by forcing `7za` to overwrite existing files with the new ones.
> Force overwrite when extracting images

- src/modules/password-for-sudo/start_chroot_script
As suggested in guysoft/OctoPi#345.
I have to admit that I wasn't able to test this yet against an actual build, but this should boil down to the same change.
> Module to revert Raspbian's "no password for sudo"

- src/variants/armbian/config
The orange Pi Zero image for example is called `Ubuntu_xenial_next.7z`, hence the pattern here doesn't match. Changing the glob mask fixes this issue.
CC #7
> Fix armbian build

- src/modules/base/start_chroot_script
`/etc/custompios_buildbase` was empty before that. And the return of `/etc/<distname>_version` trivializes figuring out what distribution version a flashed image actually runs (see also my comment on https://github.com/guysoft/OctoPi/commit/36af82350c20e69543bf3467c12fa188f08ad577 on why this is desirable to have).
> Fix /etc/custompios_buildbase & add /etc/<dist>_version

- src/build_custom_os
- src/common.sh
- src/custompios
- src/execution_order.py
- src/modules/base/end_chroot_script
- src/modules/disable-services/end_chroot_script
- src/modules/disable-services/start_chroot_script
- src/modules/ffmpeg/end_chroot_script
- src/modules/ffmpeg/start_chroot_script
- src/modules/kernel/end_chroot_script
- src/modules/kernel/start_chroot_script
- src/modules/password-for-sudo/start_chroot_script
This fixes error detection during build (see #18). All scripts were adjusted to `set -e` and an error trap was installed that when triggered unmounts the image and logs "BUILD FAILED" to console. I also added a "BUILD SUCCEEDED" message.
This has so far only been tested against the OctoPi build - it might be that in the scripts not needed for that there are still lines that can fail without any issues (e.g. trying to delete non existing files) and that need a `|| true` appended, just like it was necessary in `execute_chroot_script`.
I also had to add a `cd $DIST_PATH` into the `ERR` trap before the unmount, otherwise depending on the  location in the script the error happened the mount point would be blocked by the script itself and the forced `kill` before the unmount would thus kill the …
> Properly detect build errors

- src/modules/gui/filesystem/home/pi/scripts/enable_gpu
This bug caused matchbox to be started twice, due to an unescaped &, causing a second instance to start needlessly.
I also set compton to background mode and multi-monitor, so it will work in more conditions.
Fixes "Video Decode: Unavailable" in Chromium due to "Compositing manager: No".
To confirm this patch, you can do the following:
1. Replicate old situation:
```
sed 's@matchbox-window-manager \&@compton --backend glx --unredir-if-possible --glx-swap-method buffer-age --glx-no-stencil --paint-on-overlay --vsync opengl &\nmatchbox-window-manager \&@g' -i start_gui
```
Result:
```
[...]
compton --backend glx --unredir-if-possible --glx-swap-method buffer-age --glx-no-stencil --paint-on-overlay --vsync opengl matchbox-window-manager &
matchbox-window-manager &
[...]
```
Notice the …
> Fix regex bug in enabling compositing

- src/modules/auto-hotspot/filesystem/root/usr/bin/autohotspotN
It was causing problems in ZynthianOS, avoiding to correctly detect the configured Wifi networks and always running up the wifi hotspot.
> Remove "\r" and "\n" from captured SSIDs strings.

- src/modules/ffmpeg/start_chroot_script
Added additional switches to configure FFmpeg build for GPU-accelerated x264.
Original build instructions appear to be taken from http://www.jeffreythompson.org/blog/2014/11/13/installing-ffmpeg-for-raspberry-pi/
A newer setup is at https://www.reddit.com/r/raspberry_pi/comments/5677qw/hardware_accelerated_x264_encoding_with_ffmpeg/
> Hardware accelerated FFmpeg build

- src/variants/armbian/pre_chroot_script
The DNS server that was originally referenced is a (seemingly) random IP that happened to be a DNS server?
I've chosen the Google and Cloudflare public DNS servers for the sake of simplicity.
> pre_chroot_script: use public nameservers

- src/modules/gui/filesystem/home/pi/scripts/enable_gpu
Checks the Revision code to see if it's a pi 4 and if so removes the lines that stop FullPageOS from displaying on the monitors after the gpu enable script is run. Revision codes found here https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md
> fix for rpi 4 boot config

- src/common.sh
- src/variants/armbian/pre_chroot_script
- src/variants/bananapi-m1/pre_chroot_script
- src/variants/example/post_chroot_script
Fixes bugs:
#63 : unpack would chown the enture target dir with all existing files, and 
#64 : apt-get clean would delete cached files that are still usable, eliminating caching between builds.
My simple solution for copying files involves unnecessary disk activity, but I think the bug is big enough to warrant fixing sooner rather than later, and then refining as time allows.
> Autoclean instead of clean, fix bug with unpacking(Fix #63 and #64)

- src/modules/admin-toolkit/config
- src/modules/admin-toolkit/filesystem/home/pi/scripts/ufw_config
- src/modules/admin-toolkit/start_chroot_script
- src/modules/gui/filesystem/home/pi/scripts/enable_gpu
- src/modules/gui/filesystem/home/pi/scripts/rotate.sh
Additions:
- Rotate.sh for screen rotations
Closes: https://github.com/guysoft/FullPageOS/issues/321#issue-573471727
https://www.raspberrypi.org/forums/viewtopic.php?t=243564#p1485227
TLDR: The fkms driver while the best option for most pi's cant read the config.txt to set screen rotation on boot so we use this script and implement it in what ever way suits the specific use
Fixes:
- pi 4 revision code checking
With the release of new pi 4's there's a new revision code. Fixes https://github.com/guysoft/CustomPiOS/issues/73#issue-611470088
- Variable naming in UFW script
- admin-toolkit cronjob handling
> Fixes and Additions

- src/build
```
± ack OCTOPI_COMMIT
src/build
18:  export OCTOPI_COMMIT=`git rev-parse HEAD`
```
Its unneeded
> Remove unneeded OCTOPI_COMMIT

- src/modules/ffmpeg/start_chroot_script
This is a single issue PR.
VLC source management moved to GitLab and changed URLs at some point, per details here: http://git.videolan.org.
Trying to build a CustomPiOS distro with the ffmpeg module results in persistent failure when sourcing x264 to build. This PR just updates the new source target.
Building FFMPEG module ran successfully on Ubuntu 18.04 x86_64.
Thanks!
> Update moved x264 source URL in FFMPEG module

- src/custompios
Use copy when BASE_ZIP_IMG is an already extracted image
> Enable image copy (#84)

- src/modules/admin-toolkit/config
- src/modules/admin-toolkit/start_chroot_script
Fixes #90 and #87
(Replaces #88)
Also makes user pis pw random when custom user with password is used
> Fix admin-toolkit config

- src/release
> Fixed Image Name Handling #93

- src/Dockerfile.arm64v8
Created arm64v8 Dockerfile using arm32 one as base.
It was tested under MacOS BigSur on M1 cpu with Docker Desktop 2020-12-16 preview.
Works well without qemu emulation both for building armhf and arm64 images.
OctoPi build takes 10 minutes for armhf variant and 7 minutes for arm64.
> Dockerfile for arm64v8

- src/modules/admin-toolkit/config
- src/modules/admin-toolkit/start_chroot_script
Use id to see if the account specified already exists. If it does, skip creating it but still change the password and setup SSH keys.
This allows the module to be used to secure the pi account without having to create a new account.
Tested on one of my builds, and it changed the password and added my SSH keys perfectly.  This should only change the behaviour if you specify `ADMIN_TOOLKITNAME=pi`, which previously would cause the build to just die at the `useradd`, so it shouldn't affect any existing builds using the module.
Fixes #104
> Allow altering pi account

- src/common.sh
I am currently using this shorthand to modify / add values into `/boot/config.txt`
It does rely on `raspi-config` to get the job done. I chose to go with `raspi-config` as it gets maintained to work with the newer RPi versions, and it either uncomments the relevant config line or it appends a line "intelligently". This can replace the usual `sed` commands
Obviously, it only works if the image is RaspiOS / Raspbian, otherwise it'd be missing `raspi-config`
> Shorthand function to modify /boot/config.txt

- src/hooks/post_push
This pull request tries to address one of the issues that happened to me. When the CMake build broke (https://github.com/guysoft/CustomPiOS/issues/120) I had some days where I was blocked from making a build, because I updated the local `devel` image.
To overcome this issue, and having a more reliable build, I think it would be good to push also an `SHA-XXXXXX` tag, each time we push the `devel` image. 
Using this approach, when a new `devel` tag is pushed, the old one still remains around and can be pointed to in build processes that require a reliable configuration.
I had no way of testing this, please provide feedback, I'll be happy to keep helping to move this forward.
> Added push of SHA256 tag when pushing develop

- src/argparse.bash
This PR should allow CustomPiOS to "just run" on systems that have a `python3` executable instead of a `python` executable (like my own).
I only found usages of the host's python executable in `argparse.py`, so I've only made changes there. Let me know if I've missed anything.
> Check for python executables

- src/argparse.bash
Small change from the last PR (of the same name).
Now, the result of the `which python` commands will be directed to `/dev/null`.
> Check python executables

- README.rst
I have added FarmPi to the README file just below OctoPi. I have done this because it is used for controlling multiple OctoPrint instances.
> Add FarmPi to README.rst first

- .github/workflows/docker-build.yml
Tries to solve https://github.com/guysoft/CustomPiOS/issues/140. By default this action adds the tag of the current branch and also add the `latest` tag to the latest image pushed.
It should also add the commit sha as a tag, useful to get a specific commit image (in case of regression, etc).
Try and see if it can work for the project. Otherwise we can customize tags using the rules here https://github.com/docker/metadata-action#usage.
I tried on my end by logging out the output and all seems to be working fine.
> Add docker tags and label

- src/common.sh
* check_install_pkgs - check if pkgs is installed if not installs it.
* apt_update_skip - Skips 'apt update' if cache not older than one Hour
check_install_pkgs accepts multiple words in Variable.
As example:
Your module needs many dependencies.
Place an Variable in your config file like:
[ -n "$KLIPPER_DEPS" ] || KLIPPER_DEPS="wget git gpiod \
virtualenv python-dev \
libffi-dev build-essential \
libncurses-dev libusb-dev \
avrdude gcc-avr binutils-avr avr-libc \
stm32flash dfu-util libnewlib-arm-none-eabi \
gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0-0"
in your start_chroot_script, you can use:
apt_update_skip
check_install_pkgs $KLIPPER_DEPS
This will check your apt cache is present and if, then its time since last 'apt update'
If it is older than 1 Hour it will run 'apt update' …
> Added two 'QoL' functions to common.sh

- src/modules/gui/filesystem/home/pi/scripts/start_gui
Adds options to turn off the disabling power management and rotate the screen if required.
Depending the the use case of the OS it may be desirable to keep the standard power management options for Xorg so that the screen will blank when the input is idle for an amount of time. For example this will mean that the screen will blank until a touchscreen is touched.
Depending on the screen used, it can be rotated at an Xorg level also in the start_gui script. For my use case this is required when using a non official raspberry pi 10" touch screen in the standard case. (Official touch screens use an option in `/boot/config.txt`).
> Allow power management to be disabled and screen rotated

- src/modules/gui/filesystem/home/pi/scripts/start_gui
MR #157 broke disabling screen blanking. It has missing spaces after the [ and before the ].
I fix those and also changed [] to [[]] as it  can handle more complex conditions and is less error-prone.
I encountered this problem in the FullPageOS 0.13.0 RC1 release
> Fix broken runtime options

- src/modules/base/start_chroot_script
This should improve behavior of func create_userconf.
As discussed in #163 , this prevents build fails if using 'buster' images
Also, this upgrades 'userconf-pi' package before applying the patch.
This should prevent be overwritten by 'pkgupgrade' module.
Signed-off-by: Stephan Wendel <me@stephanwe.de>
> feat: detect os version and upgrade userconf-pi first (#163)

- src/modules/network/config
- src/modules/network/filesystem/etc/systemd/system/disable-wifi-pwr-mgmt.service
- src/modules/network/filesystem/etc/udev/rules.d/070-wifi-powersave.rules
- src/modules/network/filesystem/usr/local/bin/pwrsave
- src/modules/network/filesystem/usr/local/bin/pwrsave-udev
- src/modules/network/start_chroot_script
This changes allow to customize behavior of network modules power save
for wifi.
The used method spits out an error if the device has no wifi built in,
which confuses the user.
To prevent that I implemented a simple solution that the user only get a
warning if no wifi device present.
Also added functionality to disable the whole mechanism.
You can choose a standard rc.local entry or
a systemd service to manipulate behavior on reboots
(Enable/Disable the service)
Signed-off-by: Stephan Wendel <me@stephanwe.de>
> feat: add pwrsave script to network module

- src/modules/network/config
- src/modules/network/start_chroot_script
As mentioned in #169
I killed the whole functionality of that module.
Because Variables are declared as BASE_NETWORK,
the module will not be configured at all.
Variables has to start with module name in capital letters to be parsed
by CustomPIOS
Signed-off-by: Stephan Wendel <me@stephanwe.de>
> fix: fixes error not parsed variables #168

- src/modules/admin-toolkit/start_chroot_script
- src/modules/auto-hotspot/start_chroot_script
- src/modules/auto-mount-removable/start_chroot_script
- src/modules/base/start_chroot_script
- src/modules/disable-services/start_chroot_script
- src/modules/docker/start_chroot_script
- src/modules/ffmpeg/start_chroot_script
- src/modules/gui/start_chroot_script
- src/modules/install-linux-modules-extra/start_chroot_script
- src/modules/kernel/start_chroot_script
- src/modules/mysql/start_chroot_script
- src/modules/network/start_chroot_script
- src/modules/usage-statistics/start_chroot_script
- src/variants/armbian/pre_chroot_script
When building buster images, the change from stable to oldstable breaks some automation (including the ZynthianOS build) with a non-zero exit status and a message to the following effect:
`N: Repository 'http://raspbian.raspberrypi.org/raspbian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'`
This change allows the change in Suite value without complaint or ill effect.
> Allow change from, e.g., stable to oldstable

- src/modules/admin-toolkit/start_chroot_script
- src/modules/auto-hotspot/start_chroot_script
- src/modules/auto-mount-removable/start_chroot_script
- src/modules/base/start_chroot_script
- src/modules/disable-services/start_chroot_script
- src/modules/docker/start_chroot_script
- src/modules/ffmpeg/start_chroot_script
- src/modules/gui/start_chroot_script
- src/modules/install-linux-modules-extra/start_chroot_script
- src/modules/kernel/start_chroot_script
- src/modules/mysql/start_chroot_script
- src/modules/network/start_chroot_script
- src/modules/usage-statistics/start_chroot_script
uses --allow-relreaseinfo-change
instead of --allow-releaseinfo-change
Signed-off-by: Stephan Wendel <me@stephanwe.de>
> fix: should fix typo from pr #171

- src/modules/network/filesystem/boot/custompios-wpa-supplicant.txt
Correct typo, from `none-compatible` to `incompatible`. According to https://english.stackexchange.com/questions/55596/is-noncompatible-a-legitimate-synonym-of-incompatible, `noncompatible` isn't standard, and it doesn't include the hyphen.
> Change none-compatible to incompatible

- src/modules/base/start_chroot_script
I just started using CustomPiOS and discovered this at my logs:
```
+ apt install --yes --only-upgrade userconf-pi
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```
Here is a fix 🤗
> fix: apt vs. apt-get in base module

- src/modules/docker/start_chroot_script
The docker module did not work when selecting raspios64 as BASE_DISTRO. This tiny commit changes that (I have confirmed that it also works with raspios64 as expected)
> fix: docker now works for raspios64

- src/variants/armbian/filesystem/root/etc/network/interfaces
Without `auto eth0`, the eth0 interface stays down.
> armbian: automatically bring up eth0

- src/common.sh
- src/custompios
- src/qemu_boot.sh
- src/qemu_boot64.sh
This change allows setting a custom boot partition instead of relying on the current heuristic of either assuming it's the same as the root, or is partition 1. For example, rockpi images come with a GPT partition table where boot is partition 4 and root is 5.
The order of arguments to `mount_image` is a bit weird now, but it keeps maximum backwards compatibility.
> allow setting boot partition

- README.rst
- src/custompios
case gentoo's qemu binary name is not same as debian and other distros, build with docker and systemd-nspawn qemu is broken, need to spec binary name to use
> src/custompios: add gentoo linux build support

- src/custompios
The `arch` command isn't particularly well standardized compared to `uname -m`. For example, coreutils on Archlinux doesn't provide it, and it's generally not recommended to rely on it.
See e.g. https://www.gnu.org/software/coreutils/manual/html_node/arch-invocation.html:
> arch is not installed by default, so portable scripts should not rely on its existence.
> replace arch with uname -m

- src/modules/base/config
- src/modules/base/end_chroot_script
While b47534cc33a0b65ea5d2ee107cefda66470cb226 provides a `PKGUPGRADE_CLEANUP` variable to prevent the `pkgupgrade` module from running `apt-get clean` in the cleanpu script, the `base` module still unconditionally clears the apt-cache: https://github.com/guysoft/CustomPiOS/blob/8a3a002570c46409372349853622f0619baefc87/src/modules/base/end_chroot_script#L41-L42
This PR introduces a new `BASE_APT_CLEAN` variable, that can be set to anything but the default `yes` to prevent `apt-get clean` from being run.
while I edited the files i couldn't resist the urge to drop some unnecessary bashisms and replace the oldstyle command substitution ` `` ` with the modern, stackable ` $() ` (but these changes are in separate commits, so feel free to ignore them)
> more preventing of "apt clean"

- src/custompios
- everybody should probably be able to read the file
- **not** everybody (esp. not "others") should be able to write the generated file
- nobody needs to be able to execute the file
Closes: https://github.com/guysoft/CustomPiOS/issues/211
> Fix permission of generated image to to 644

- src/modules/base/end_chroot_script
- src/modules/base/start_chroot_script
Includes changes if resolv.conf is a symbolic link
Mostly affected are armbian based images.
If you want to go through whole logs of build please see:
https://github.com/KwadFan/MainsailOS-dev/actions/runs/10264062537
As earlier said on discord:
What it does:
1. Checking if resolv.conf is a symlink, if yes store target location in a temporary file on /
2. Altering resolv.conf, based on setup either your desired default or based on `BASE_USE_ALT_DNS`
3. After all desired modules, running end_chroot and restore either link or backuped resolv.conf(depending if temporary file exist)
I think this is less invasive as PR #224
Regards Kwad
> fix: fix handling of resolv.conf file

- src/custompios_core/base_image_downloader.py
- src/images.yml
- src/modules/base/start_chroot_script
- src/modules/disable-services/start_chroot_script
This is work in progress that I want to merge once we get CustomPiOS V2 in devel.
It can download and run the board similar to how images are downloaded for rpi.
The wifi configuration is not as simple yet like in raspberrypi because the images of Libre.computer have no fat32 partition to put configurations in. But this does build a working OctoPi.
> Support librecomputer Le Potato AML-S905X-CC Debian image board

- src/custompios_core/base_image_downloader.py
- src/images.yml
- src/modules/base/start_chroot_script
- src/modules/disable-services/start_chroot_script
Support librecomputer Le Potato AML-S905X-CC Debian image
It can download and run the board similar to how images are downloaded for rpi.
The wifi configuration is not as simple yet like in raspberrypi because the images of Libre.computer have no fat32 partition to put configurations in. But this does build a working OctoPi.
> Support librecomputer Le Potato AML-S905X-CC Debian image
